volumes:
  v_maria:
    name : v_maria
    driver: local
    driver_opts:
      type: none
      device: /home/tnaceur/data/mariadb
      o: bind
  v_wp:
    name : v_wp
    driver: local
    driver_opts:
      type: none
      device: /home/tnaceur/data/wordpress
      o: bind

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    pull_policy: never
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - v_wp:/var/www/html
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    pull_policy: never
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - v_wp:/var/www/html
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    pull_policy: never
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - v_maria:/var/lib/mysql