networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    pull_policy: never
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    pull_policy: never
    env_file:
      - .env
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    pull_policy: never
    env_file:
      - .env
    networks:
      - inception